fasdkfjasd

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -1,27 +1,32 @@
-name: CI
-
+name: PR checks
 on:
-  pull_request:
-    branches:
-      - main
-
+    pull_request:
+        types: [opened, synchronize, reopened]
 jobs:
-  build:
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v2
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '18'
-
-      - name: Install dependencies
-        run: npm ci
-
-      - name: Lint code
-        run: npm run lint
-
-      - name: Run tests
-        run: npm run test
+    run_checks:
+        runs-on: ubuntu-latest
+        strategy:
+            matrix:
+                node-version: [20]
+        steps:
+            - name: Checkout
+              uses: actions/checkout@v4.1.7
+            - name: Setup Node.js environment
+              uses: actions/setup-node@v4.0.3
+              with:
+                node-version: '${{ matrix.node-version }}'
+            - name: Install dependencies
+              run: npm ci
+            - name: Run lint
+              run: npm run lint
+            - name: Run tests
+              run: npm run test
+    cancel_merge:
+        runs-on: ubuntu-latest
+        needs: [run_checks]
+        steps:
+          - name: Cancel the merger if the checks fail
+            if: failure()
+            run: |
+                echo "Checks failed. Cancelling the merge."
+                exit 1
